{
  "contest": 219,
  "handle": "SaeedAlipoor01988",
  "risk": "2",
  "title": "The possibility of encountering a DOS in the DAO.sol.execute function",
  "issueId": 17,
  "issueUrl": "https://github.com/code-423n4/2023-03-aragon-findings/issues/17"
}